# -------- 基本站点信息 --------
title: Life Veda
description: Investment Analysis, Market Insights, and Trading Strategies
lang: zh-CN               # 新增：站点默认语言
url: "https://4lifeveda.com"   # 新增：域名（不要带末尾 /）
baseurl: ""               # 根目录部署留空

# -------- 主题与资源 --------
theme: jekyll-theme-modernist
favicon: favicon.ico
google_analytics: G-M9RR9YXJF6

# -------- 插件（GitHub Pages 白名单）--------
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  # 若你想启用远程主题，再取消注释下一行并在 plugins 中保留：
  # - jekyll-remote-theme

# remote_theme: pages-themes/modernist@v0.2.0   # 如无特别需求可保持注释
# show_downloads: false                         # Modernist 主题未使用，可留可删
