#remote_theme: pages-themes/modernist@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Life Veda
description: Gaming, Investing, Learning Math.
show_downloads: false
google_analytics: G-M9RR9YXJF6
theme: jekyll-theme-modernist
favicon: favicon.ico
